services:
  - type: web
    name: your-vite-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    redirects:
      - source: /*
        destination: /index.html
        statusCode: 200
